version: '3.3'
services:
    app:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: app
        hostname: app
        image: app
        volumes:
            - .:/app
        ports:
            - 127.0.0.1:8000:8000
        restart: always
        depends_on:
            - db
    db:
        image: postgres
        container_name: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        volumes:
            - local_pgdata:/var/lib/postgresql/data

volumes:
    local_pgdata:
