version: '3.9'
services:
  fastapi-template:
    build:
      dockerfile: Dockerfile

    container_name: fastapi-template
    hostname: fastapi-template
    image: fastapi-template
    volumes:
      - .:/fastapi-template
      - ./logs:/logs
    ports:
      - "8000:8000"
    restart: always
    networks:
      - fastapi-template-network

networks:
  fastapi-template-network:
    driver: bridge