version: '3.9'
services:
  playground-api:
    build:
      dockerfile: Dockerfile

    container_name: playground-api
    hostname: playground-api
    image: playground-api
    volumes:
      - .:/playground-api
      - ./logs:/logs
    ports:
      - "8000:8000"
    restart: always
    networks:
      - flio-ai-network

networks:
  flio-ai-network:
    external:
      name: flio-ai-network