from .generic import AUTHORIZATION_ERROR, NOT_FOUND_ERROR, BAD_REQUEST_ERROR, METHOD_NOT_ALLOWED_ERROR


__all__ = [
    "AUTHORIZATION_ERROR",
    "NOT_FOUND_ERROR",
    "BAD_REQUEST_ERROR",
    "METHOD_NOT_ALLOWED_ERROR",
]